filebeat:
  filebeat.modules:
    - module: nginx    
    
  autodiscover.providers:
    - type: docker
      templates:
        - condition.contains:
            docker.container.image: nginx
          config:
            - module: nginx
              access:
                enabled: true
                input:
                  type: container
                  paths:
                    - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
              error:
                enabled: true
                input:
                  type: container
                  paths:
                    - "/var/lib/docker/containers/${data.docker.container.id}/*.log"

setup.dashboards:
  enabled: true

output.elasticsearch:
  hosts: [$ELASTICSEARCH_HOSTS]
  username: $ELASTICSEARCH_USERNAME
  password: $ELASTICSEARCH_PASSWORD

setup.kibana:
  host: $KIBANA_HOST
  username: $ELASTICSEARCH_USERNAME
  password: $ELASTICSEARCH_PASSWORD
