filebeat:
  autodiscover.providers:
    - type: docker
      templates:
        - condition.contains:
            docker.container.image: hi-service
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              json:
                keys_under_root: true
                add_error_key: true
                # message_key: "log"
                overwrite_keys: true
              processors:
                # - drop_fields:
                #     fields: ["service"]
                # - decode_json_fields:
                #     fields: ["message"]
                #     max_depth: 4
                # - rename:
                #     fields:
                #       - from: "service"
                #         to: "service_doc"
                #       - from: "message"
                #         to: "message_doc"

output.elasticsearch:
  hosts: "${ELASTICSEARCH_HOSTS}"
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"
  index: "hi-service-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.kibana:
  host: "${KIBANA_HOST}"
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

# output.file:
#   path: "/usr/share/filebeat/log"
#   filename: test.log

  # processors:
  #   - decode_json_fields:
  #       fields: ["message"]
  #       process_array: false
  #       max_depth: 2

# setup.template:
#   name: "hi-service"
#   pattern: "hi-service-*"

setup.template.json:
  enabled: true
  path: "template.json"
  name: "hi-service"

setup.ilm:
  enabled: false
