version: "3.7"

services:
  elasticsearch:
    image: marshalw/elasticsearch-customer-analyzer
    container_name: elasticsearch
    environment:
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      xpack.security.enabled: "true"
      discovery.type: single-node
      TAKE_FILE_OWNERSHIP: "true"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms16g -Xmx16g"
      cluster.max_shards_per_node: 30000
      xpack.monitoring.collection.enabled: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:$ELK_VERSION
    container_name: kibana
    volumes:
      - ./kibana/config.yml:/usr/share/kibana/config/kibana.yml
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: $ELASTIC_USER
      ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
    # depends_on:
    #   - elasticsearch

  spider:
    image: marshalw/spider-service
    container_name: spider
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./spider/config:/app/config:ro
      - ./spider/cache:/app/cache
      - ./spider/http-cache/:/usr/src/app/cache

  filebeat_spider:
    image: docker.elastic.co/beats/filebeat:$ELK_VERSION
    container_name: filebeat-spider
    user: root
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    volumes:
      - ./filebeat-spider/ilm.json:/usr/share/filebeat/ilm.json:ro
      - ./filebeat-spider/fields.yml:/usr/share/filebeat/custom.yml:ro
      - ./filebeat-spider/config.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./filebeat-spider/data:/usr/share/filebeat/data
    environment:
      ELASTICSEARCH_HOSTS: localhost:9200
      KIBANA_HOST: localhost:5601
      ELASTICSEARCH_USERNAME: $ELASTIC_USER
      ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
    command: ["--strict.perms=false", "-e"]
    restart: on-failure
    # depends_on:
    #   - elasticsearch
    #   - kibana
    #   - spider

  web_logger:
    container_name: web-logger
    restart: always
    image: marshalw/web-logger
    ports:
      - "10086:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    volumes:
      - /etc/localtime:/etc/localtime:ro

  filebeat_web_logger:
    image: docker.elastic.co/beats/filebeat:$ELK_VERSION
    container_name: filebeat-web-logger
    user: root
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    volumes:
      - ./filebeat-web-logger/ilm.json:/usr/share/filebeat/ilm.json:ro
      - ./filebeat-web-logger/fields.yml:/usr/share/filebeat/custom.yml:ro
      - ./filebeat-web-logger/config.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      ELASTICSEARCH_HOSTS: localhost:9200
      KIBANA_HOST: localhost:5601
      ELASTICSEARCH_USERNAME: $ELASTIC_USER
      ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
    command: ["--strict.perms=false", "-e"]
    restart: on-failure
    # depends_on:
    #   - elasticsearch
    #   - kibana
    #   - web_logger

  metricbeat_system:
    image: docker.elastic.co/beats/metricbeat:$ELK_VERSION
    container_name: metricbeat-system
    user: root
    network_mode: "host"
    volumes:
      - ./metricbeat-system/config.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    environment:
      ELASTICSEARCH_HOSTS: localhost:9200
      KIBANA_HOST: localhost:5601
      ELASTICSEARCH_USERNAME: $ELASTIC_USER
      ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]

networks:
  default:
    name: $DEFAULT_NETWORK
