version: "3.7"

services:
  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        - ELK_VERSION=$ELK_VERSION
    container_name: elasticsearch
    environment:
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      xpack.security.enabled: "true"
      discovery.type: single-node
      TAKE_FILE_OWNERSHIP: "true"
      ELK_VERSION: $ELK_VERSION
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

networks:
  default:
    name: $DEFAULT_NETWORK
