version: "3.7"

services:
  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch
    environment:
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      xpack.security.enabled: "true"
      discovery.type: single-node
      TAKE_FILE_OWNERSHIP: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:$ELK_VERSION
    container_name: kibana
    volumes:
      - ./kibana/config.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: $ELASTIC_USER
      ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
    depends_on:
      - elasticsearch

  spider:
    image: marshalw/spider-service
    container_name: spider
    volumes:
      - ./spider/config.yml:/usr/src/app/config/spider.yml
      - ./spider/cache:/usr/service/app/cache
    command: ["*/20 * * * * /start.sh"]

  echo:
    image: marshalw/echo-service
    container_name: echo

  filebeat_echo:
    image: docker.elastic.co/beats/filebeat:$ELK_VERSION
    container_name: filebeat-echo
    user: root
    network_mode: "host"
    volumes:
      - ./filebeat-echo/custom.yml:/usr/share/filebeat/custom.yml:ro
      - ./filebeat-echo/config.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      ELASTICSEARCH_HOSTS: localhost:9200
      KIBANA_HOST: localhost:5601
      ELASTICSEARCH_USERNAME: $ELASTIC_USER
      ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
    command: ["--strict.perms=false", "-e"]
    restart: on-failure
    depends_on:
      - elasticsearch
      - kibana
      - echo

  # filebeat_spider:
  #   image: docker.elastic.co/beats/filebeat:$ELK_VERSION
  #   container_name: filebeat-spider
  #   user: root
  #   network_mode: "host"
  #   volumes:
  #     - ./filebeat/fields.yml:/usr/share/filebeat/fields.yml:ro
  #     - ./filebeat/config.yml:/usr/share/filebeat/filebeat.yml:ro
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   environment:
  #     ELASTICSEARCH_HOSTS: localhost:9200
  #     KIBANA_HOST: localhost:5601
  #     ELASTICSEARCH_USERNAME: $ELASTIC_USER
  #     ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
  #   command: ["--strict.perms=false", "-e"]
  #   restart: on-failure
  #   depends_on:
  #     - elasticsearch
  #     - kibana
  #     - spider

networks:
  default:
    name: $DEFAULT_NETWORK
