version: "3.7"

services:
  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch
    environment:
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      xpack.security.enabled: "true"
      discovery.type: single-node
      TAKE_FILE_OWNERSHIP: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:$ELK_VERSION
    container_name: kibana
    volumes:
      - ./kibana/config.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: $ELASTIC_USER
      ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
    depends_on:
      - elasticsearch

  packetbeat:
    image: docker.elastic.co/beats/packetbeat:$ELK_VERSION
    container_name: packetbeat
    user: root
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./packetbeat/config.yml:/usr/share/packetbeat/packetbeat.yml
    environment:
      ELASTICSEARCH_HOSTS: localhost:9200
      KIBANA_HOST: localhost:5601
      ELASTICSEARCH_USERNAME: $ELASTIC_USER
      ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
    cap_add:
      - NET_RAW
      - NET_ADMIN
    command: ["--strict.perms=false"]
    restart: on-failure
    depends_on:
      - elasticsearch
      - kibana

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:$ELK_VERSION
    container_name: metricbeat
    user: root
    network_mode: "host"
    volumes:
      - ./metricbeat/config.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    environment:
      ELASTICSEARCH_HOSTS: localhost:9200
      KIBANA_HOST: localhost:5601
      ELASTICSEARCH_USERNAME: $ELASTIC_USER
      ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    restart: on-failure
    depends_on:
      - elasticsearch
      - kibana

  filebeat:
    image: docker.elastic.co/beats/filebeat:$ELK_VERSION
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/config.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat/log:/usr/share/filebeat/log
    environment:
      ELASTICSEARCH_HOSTS: elasticsearch:9200
      KIBANA_HOST: kibana:5601
      ELASTICSEARCH_USERNAME: $ELASTIC_USER
      ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
    command: ["--strict.perms=false"]
    restart: on-failure
    depends_on:
      - elasticsearch
      - kibana
      - hi_service

  hi_service:
    image: marshalw/hi-service
    container_name: hi_service
    ports:
      - 8888:8888

networks:
  default:
    name: $DEFAULT_NETWORK
