version: "3.7"

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:$ELK_VERSION
    container_name: filebeat
    user: root
    network_mode: "host"
    volumes:
      - ./filebeat/config.yml:/usr/share/packetbeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: ["--strict.perms=false"]
