server.name: kibana
server.host: "0"
elasticsearch.hosts: ["$ELASTICSEARCH_HOSTS"]
elasticsearch.username: $ELASTICSEARCH_USERNAME
elasticsearch.password: $ELASTICSEARCH_PASSWORD
# i18n.locale: "zh-CN"


# https://discuss.elastic.co/t/kibana-warning-on-control-visualization-terms-list-might-be-incomplete/228338
# 不是问题，取消下面的设置
# kibana.autocompleteTerminateAfter: 10000000
# kibana.autocompleteTimeout: 5000
