filebeat:
  autodiscover.providers:
    - type: docker
      templates:
        - condition.contains:
            docker.container.image: spider-service
          config:
            - type: container
              # exclude_lines: ['^crond:']
              include_lines: ['^{']
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              json:
                keys_under_root: true
                message_key: message
                
              # processors:
              #   - drop_event:
              #       when:
              #         regexp:
              #           message: "^crond:.*"
              #   - decode_json_fields:
              #       # target: ""
              #       fields: ["message"]

setup.ilm:
  enabled: false

setup.template.name: "filebeat-spider"
setup.template.pattern: "filebeat-spider-*"
setup.template.overwrite: true
setup.template.fields: "custom.yml"

output.elasticsearch:
  hosts: "${ELASTICSEARCH_HOSTS}"
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"
  index: "filebeat-spider-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.kibana:
  host: "${KIBANA_HOST}"
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}
