filebeat:
  autodiscover.providers:
    - type: docker
      templates:
        - condition.contains:
            docker.container.image: spider-service
          config:
            - type: container
              # exclude_lines: ['^crond:']
              # include_lines: ['^{']
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              # json:
              #   keys_under_root: true
              #   message_key: message

              processors:
                - drop_event:
                    when:
                      regexp:
                        message: "^crond:.*"
                - decode_json_fields:
                    fields: ["message"]
                    target: ""
                    overwrite_keys: true

setup.ilm:
  enabled: true
  rollover_alias: "filebeat-spider"
  pattern: "{now/d}-000001"
  policy_file: "ilm.json"

setup.template.name: "filebeat-spider"
setup.template.pattern: "filebeat-spider-*"
setup.template.overwrite: true
setup.template.fields: "custom.yml"

setup.kibana:
  host: "${KIBANA_HOST}"
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

output.elasticsearch:
  hosts: "${ELASTICSEARCH_HOSTS}"
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"
  index: "filebeat-spider-%{[agent.version]}-%{+yyyy.MM.dd}"

monitoring.enabled: true
