from: !!str '光明网'
section: !!str '光明日报'
cachePath: ./cache/光明网-光明日报
urls:
  - http://news.gmw.cn/node_4108.htm
domainWhitelist:
  - news.gmw.cn
maxDepth: 5
timeout: !!int 60000 #超时
interval: !!int 1500 #请求间隔
maxConcurrency: 100 #同时的请求数
logging:
  level: debug
respectRobotsTxt: false
rules:
  fetch:
    - !!js/regexp ^\/node_4108_.* # 列表分页
    - !!js/regexp \/([1-3]\d{3}-(0[1-9]|1[0-2])\/(0[1-9]|[12]\d|3[01])).* # 文章
  parse:
    - !!js/regexp \/([1-3]\d{3}-(0[1-9]|1[0-2])\/(0[1-9]|[12]\d|3[01])).* # 文章
  item:
    - name: title # 标题
      expression: //h1[@class="u-title"]
    - name: content # 正文
      expression: //div[@class="u-mainText"]
    # - name: publishdate # 发布日期
    #   expression: //meta[@name="publishdate"]/@content
